/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface JuicePrice { 'juiceSize' : JuiceSize, 'price' : bigint }
export interface JuiceSize { 'size' : bigint, 'juice' : string }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface Transaction {
  'transactionType' : { 'teacherFree' : null } |
    { 'stripePaid' : null },
  'size' : bigint,
  'juice' : string,
  'timestamp' : Time,
  'teacherPrincipal' : [] | [Principal],
  'transactionStatus' : { 'failure' : { 'reason' : string } } |
    { 'success' : null },
  'price' : bigint,
  'transactionId' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VendingConfig {
  'vendingUrl' : string,
  'sizeOptions' : Array<bigint>,
  'juiceTypes' : Array<string>,
  'prices' : Array<[JuiceSize, bigint]>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canTeacherDispenseForFree' : ActorMethod<[], boolean>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJuicePrice' : ActorMethod<[JuiceSize], bigint>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getPrices' : ActorMethod<[], Array<JuicePrice>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTeacherFreeChances' : ActorMethod<[], bigint>,
  'getTeacherTransactions' : ActorMethod<[Principal], Array<Transaction>>,
  'getTransaction' : ActorMethod<[bigint], Transaction>,
  'getTransactionRange' : ActorMethod<[bigint, bigint], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendingConfig' : ActorMethod<[], [] | [VendingConfig]>,
  'initializeTeacherAccount' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUserEligibleForFreeDispense' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPrice' : ActorMethod<[JuicePrice], undefined>,
  'setPrices' : ActorMethod<[Array<JuicePrice>], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateVendingConfig' : ActorMethod<[VendingConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];