/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const JuiceSize = IDL.Record({ 'size' : IDL.Nat, 'juice' : IDL.Text });
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'transactionType' : IDL.Variant({
    'teacherFree' : IDL.Null,
    'stripePaid' : IDL.Null,
  }),
  'size' : IDL.Nat,
  'juice' : IDL.Text,
  'timestamp' : Time,
  'teacherPrincipal' : IDL.Opt(IDL.Principal),
  'transactionStatus' : IDL.Variant({
    'failure' : IDL.Record({ 'reason' : IDL.Text }),
    'success' : IDL.Null,
  }),
  'price' : IDL.Nat,
  'transactionId' : IDL.Nat,
});
export const JuicePrice = IDL.Record({
  'juiceSize' : JuiceSize,
  'price' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const VendingConfig = IDL.Record({
  'vendingUrl' : IDL.Text,
  'sizeOptions' : IDL.Vec(IDL.Nat),
  'juiceTypes' : IDL.Vec(IDL.Text),
  'prices' : IDL.Vec(IDL.Tuple(JuiceSize, IDL.Nat)),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canTeacherDispenseForFree' : IDL.Func([], [IDL.Bool], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJuicePrice' : IDL.Func([JuiceSize], [IDL.Nat], []),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getPrices' : IDL.Func([], [IDL.Vec(JuicePrice)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTeacherFreeChances' : IDL.Func([], [IDL.Nat], ['query']),
  'getTeacherTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
  'getTransactionRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendingConfig' : IDL.Func([], [IDL.Opt(VendingConfig)], ['query']),
  'initializeTeacherAccount' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserEligibleForFreeDispense' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPrice' : IDL.Func([JuicePrice], [], []),
  'setPrices' : IDL.Func([IDL.Vec(JuicePrice)], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateVendingConfig' : IDL.Func([VendingConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const JuiceSize = IDL.Record({ 'size' : IDL.Nat, 'juice' : IDL.Text });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'transactionType' : IDL.Variant({
      'teacherFree' : IDL.Null,
      'stripePaid' : IDL.Null,
    }),
    'size' : IDL.Nat,
    'juice' : IDL.Text,
    'timestamp' : Time,
    'teacherPrincipal' : IDL.Opt(IDL.Principal),
    'transactionStatus' : IDL.Variant({
      'failure' : IDL.Record({ 'reason' : IDL.Text }),
      'success' : IDL.Null,
    }),
    'price' : IDL.Nat,
    'transactionId' : IDL.Nat,
  });
  const JuicePrice = IDL.Record({ 'juiceSize' : JuiceSize, 'price' : IDL.Nat });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const VendingConfig = IDL.Record({
    'vendingUrl' : IDL.Text,
    'sizeOptions' : IDL.Vec(IDL.Nat),
    'juiceTypes' : IDL.Vec(IDL.Text),
    'prices' : IDL.Vec(IDL.Tuple(JuiceSize, IDL.Nat)),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canTeacherDispenseForFree' : IDL.Func([], [IDL.Bool], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJuicePrice' : IDL.Func([JuiceSize], [IDL.Nat], []),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getPrices' : IDL.Func([], [IDL.Vec(JuicePrice)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTeacherFreeChances' : IDL.Func([], [IDL.Nat], ['query']),
    'getTeacherTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
    'getTransactionRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendingConfig' : IDL.Func([], [IDL.Opt(VendingConfig)], ['query']),
    'initializeTeacherAccount' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserEligibleForFreeDispense' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPrice' : IDL.Func([JuicePrice], [], []),
    'setPrices' : IDL.Func([IDL.Vec(JuicePrice)], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateVendingConfig' : IDL.Func([VendingConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };